import { Plato } from './plato';


export const PLATOS: Plato[] = [
	{
		nombre: 'Pizza Pepperone Picante',
		precio: 11.60,
		restaurante: 'Tagliatella',
		ingredientes: [
			'queso',
			'tomate',
			'mozzarella',
			'salami',
			'salami picante'
		],
		descripcion: 'Tomate, Mozzarella, Salami Picante',
		categoria: 'pizzas',
		cantidad: 'para una persona',
		pic: 'picante',
		temp: 'caliente',
		alergia:[],
		preferencia: '',
		foto: 'https://res.cloudinary.com/hesvvq3zo/image/upload/w_1000,h_500,c_pad,q_30/v1477472361/takeaway/Le-Pizze-Pepperoni.jpg'
	},
	{
		nombre: 'Pizza 4 quesos',
		precio: 12.60,
		restaurante: 'Tagliatella',
		ingredientes: [
			'queso',
			'tomate',
			'grana padano',
			'mozzarella',
			'gorgonzola',
			'emmental'
		],
		descripcion: 'Tomate, Grana Padano, Mozzarella, Gorgonzola, Emmental.',
		categoria: 'pizzas',
		cantidad: 'para una persona',
		pic: 'nada picante',
		temp: 'caliente',
		alergia:[],
		preferencia: '',
		foto: 'https://res.cloudinary.com/hesvvq3zo/image/upload/w_1000,h_500,c_pad,q_30/v1477472361/takeaway/Le-Pizze-4formaggi.jpg'
	},
	{
		nombre: 'Pizza Carbonara',
		precio: 9,
		restaurante: 'TelePizza',
		ingredientes: [
			'bacon',
			'queso',
			'crema',
			'champiñon',
			'carbonara',
			'salsa carbonara',
			'mozzarella'
		],
		descripcion: 'Masa fresca, doble de bacon, champiñón, salsa carbonara, topping a base de mozzarella y extra detopping a base de mozzarella.',
		categoria: 'pizzas',
		cantidad: 'para una persona',
		pic: 'nada picante',
		temp: 'caliente',
		alergia:[],
		preferencia: '',
		foto: 'https://images.telepizza.com/vol/es/images/content/productos/pcaq_c.png'
	},
	{
		nombre: 'Pizza Boloñesa',
		precio: 7,
		restaurante: 'TelePizza',
		ingredientes: [
			'vacuno',
			'mozzarella',
			'tomate confitado',
			'tomate',
			'queso'
		],
		descripcion: 'Doble ración de carne de vacuno, topping a base de mozzarella y extra de salsa de tomate confitado.',
		categoria: 'pizzas',
		cantidad: 'para una persona',
		pic: 'nada picante',
		temp: 'caliente',
		alergia:[],
		preferencia: '',
		foto: 'https://images.telepizza.com/vol/es/images/content/productos/bolo_c.png'
	},
	{
		nombre: 'Pizza Hawaiana',
		precio: 7,
		restaurante: 'TelePizza',
		ingredientes: [
			'masa fresca',
			'york',
			'jamón york',
			'piña',
			'mozzarella',
			'tomate',
			'queso'
		],
		descripcion: 'Masa fresca, doble de york, piña, topping a base de mozzarella, tomate y extra de topping a base de mozzarella.',
		categoria: 'pizzas',
		cantidad: 'para compartir',
		pic: 'nada picante',
		temp: 'caliente',
		alergia:[],
		preferencia: '',
		foto: 'https://images.telepizza.com/vol/es/images/content/productos/phw_c.png'
	},
	{
		nombre: 'Pizza Carbonara Cebolla',
		precio: 7,
		restaurante: 'TelePizza',
		ingredientes: [
			'masa fresca',
			'bacon',
			'champiñon',
			'salsa carbonara',
			'mozzarella',
			'cebolla',
			'crema',
			'carbonara',
			'queso'
		],
		descripcion: 'Masa fresca, doble de bacon, champiñón, salsa carbonara, topping a base de mozzarella y cebolla',
		categoria: 'pizzas',
		cantidad: 'para compartir',
		pic:'nada picante',
		temp:'caliente',
		alergia:[],
		preferencia: '',
		foto: 'https://images.telepizza.com/vol/es/images/content/productos/pcar_c.png'
	},
	{
		nombre: 'Pizza Rodeo',
		precio: 7,
		restaurante: 'TelePizza',
		ingredientes: [
			'vacuno',
			'bacon',
			'salsa steak',
			'salsa grill',
			'mozzarella',
			'queso'
		],
		descripcion: 'La nueva Telepizza Rodeo compuesta por: carne de vacuno, bacon, salsa steak&grill y topping a base de mozzarella',
		categoria: 'pizzas',
		cantidad: 'para compartir',
		pic:'nada picante',
		temp:'caliente',
		alergia:[],
		preferencia: '',
		foto: 'https://images.telepizza.com/vol/es/images/content/productos/rode_c.png'
	},
	{
		nombre: 'Pizza Ibérica de TelePizza',
		precio: 7,
		restaurante: 'TelePizza',
		ingredientes: [
			'jamón ibérico de cebo',
			'tomate natural',
			'aceite de oliva',
			'masa fresca',
			'jamón',
			'tomate',
			'aceite',
			'queso'
		],
		descripcion: 'Una exquisita selección de jamón ibérico de cebo acompañado de finas rodajas de tomate natural y un toque de aceite de oliva sobre una crujiente masa',
		categoria: 'pizzas',
		cantidad: 'para compartir',
		pic:'nada picante',
		temp:'caliente',
		alergia:[],
		preferencia: '',
		foto: 'https://images.telepizza.com/vol/es/images/content/productos/iber_c.png'
	},
	{
		nombre: 'Pizza Burger',
		precio: 7,
		restaurante: 'TelePizza',
		ingredientes: [
			'queso cheddar',
			'cheddar',
			'vacuno',
			'tomate natural',
			'tomate',
			'pepinillos',
			'mozzarella',
			'bacon cripsy',
			'bacon',
			'salsa burger',
			'queso'
		],
		descripcion: 'Auténtico sabor burger en cada bocado. Queso cheddar, carne de vacuno, tomate natural y pepinillos, cubiertos con una masa con topping a base de mozzarella, bacon crispy y salsa burger.',
		categoria: 'pizzas',
		cantidad: 'para compartir',
		pic:'nada picante',
		temp:'caliente',
		alergia:[],
		preferencia: '',
		foto: 'https://images.telepizza.com/vol/es/images/content/productos/p3pb_c.png'
	},
	{
		nombre: 'Pizza Barbacoa Gourmet',
		precio: 7,
		restaurante: 'TelePizza',
		ingredientes: [
			'5 quesos',
			'pollo marinado',
			'pollo',
			'bacon ahumado',
			'bacon',
			'carne de vacuno',
			'vacuno',
			'salsa barbacoa',
			'barbacoa',
			'mozzarella',
			'queso'
		],
		descripcion: 'Una mezcla de 5 quesos, tiras de pollo marinado, bacon ahumado, doble ración de carne de vacuno, salsa barbacoa y topping a base de mozzarella.',
		categoria: 'pizzas',
		cantidad: 'para compartir',
		pic:'nada picante',
		temp:'caliente',
		alergia:[],
		preferencia: '',
		foto: 'https://images.telepizza.com/vol/es/images/content/productos/53bq_c.png'
	},
	{
		nombre: 'Pizza Carbonara Gourmet Queso',
		precio: 7,
		restaurante: 'TelePizza',
		ingredientes: [
			'5 quesos',
			'gourmet',
			'masa fina',
			'bacon',
			'champiñón',
			'salsa carbonara',
			'carbonara',
			'mozzarella',
			'queso'			
		],
		descripcion: 'Una pizza mediana mezcla de 5 quesos cubierta de una masa fina con doble ración de bacon, champiñón, salsa carbonara y extra de topping a base de mozzarella',
		categoria: 'pizzas',
		cantidad: 'para compartir',
		pic:'nada picante',
		temp:'caliente',
		alergia:[],
		preferencia: '',
		foto: 'https://images.telepizza.com/vol/es/images/content/productos/tkgq_c.png'
	},
	{
		nombre: 'Pizza Carbonara Gourmet Cebolla',
		precio: 7,
		restaurante: 'TelePizza',
		ingredientes: [
			'5 quesos',
			'masa fina',
			'bacon',
			'champiñón',
			'salsa carbonara',
			'carbonara',
			'cebolla',
			'queso'
		],
		descripcion: 'Una pizza mediana mezcla de 5 quesos cubierta de una masa fina con doble ración de bacon, champiñón, salsa carbonara y cebolla.',
		categoria: 'pizzas',
		cantidad: 'para compartir',
		pic:'nada picante',
		temp:'caliente',
		alergia:[],
		preferencia: '',
		foto: 'https://images.telepizza.com/vol/es/images/content/productos/tkgo_c.png'
	},
	{
		nombre: 'Pizza Telepizza Vulcano Nachos',
		precio: 7,
		restaurante: 'TelePizza',
		ingredientes: [
			'5 quesos',
			'masa fina',
			'bacon',
			'champiñón',
			'salsa carbonara',
			'carbonara',
			'cebolla',
			'queso'
		],
		descripcion: 'Una pizza mediana mezcla de 5 quesos cubierta de una masa fina con doble ración de bacon, champiñón, salsa carbonara y cebolla.',
		categoria: 'pizzas',
		cantidad: 'para compartir',
		pic:'nada picante',
		temp:'caliente',
		alergia:[],
		preferencia: '',
		foto: 'https://images.telepizza.com/vol/es/images/content/productos/tkgo_c.png'
	},
	{
		nombre: 'Pizza Bacon Cheeseburger',
		precio: 7,
		restaurante: 'TelePizza',
		ingredientes: [
			'masa fresca',
			'bacon',
			'mini hamburguesas',
			'hamburguesa',
			'queso cheddar',
			'cheddar',
			'mozzarella',
			'salsa burger',
			'tomate natural',
			'tomate',
			'queso'
		],
		descripcion: 'Masa fresca, bacon, mini hamburguesitas, queso cheddar, topping a base de mozzarella, salsa burger y tomate natural.',
		categoria: 'pizzas',
		cantidad: 'para compartir',
		pic:'nada picante',
		temp:'caliente',
		alergia:[],
		preferencia: '',
		foto: 'https://images.telepizza.com/vol/es/images/content/productos/pzbc_c.png'
	},
	{
		nombre: 'Pizza Barbacoa Crème Queso',
		precio: 7,
		restaurante: 'TelePizza',
		ingredientes: [
			'masa fresca',
			'bacon',
			'champiñón',
			'pollo',
			'mozzarella',
			'salsa barbacoa',
			'salsa carbonara',
			'carbonara',
			'barbacoa',
			'queso'
		],
		descripcion: 'Masa fresca, bacon, champiñón, pollo, topping a base de mozzarella, mezcla de salsa barbacoa y carbonara y extra de topping a base de mozzarella.',
		categoria: 'pizzas',
		cantidad: 'para compartir',
		pic:'nada picante',
		temp:'caliente',
		alergia:[],
		preferencia: '',
		foto: 'https://images.telepizza.com/vol/es/images/content/productos/pbcq_c.png'
	},
	{
		nombre: 'Pizza Jalisco',
		precio: 7,
		restaurante: 'TelePizza',
		ingredientes: [
			'masa fresca',
			'aceitunas negras',
			'aceitunas',
			'cebolla',
			'pimiento morrón',
			'vacuno',
			'queso'
		],
		descripcion: 'Masa fresca, Aceitunas negras, Cebolla, Pimiento morrón, carne de vacuno',
		categoria: 'pizzas',
		cantidad: 'para compartir',
		pic:'nada picante',
		temp:'caliente',
		alergia:[],
		preferencia: '',
		foto: 'https://images.telepizza.com/vol/es/images/content/productos/jali_c.png'
	},
	{
		nombre: 'Chicken McRoll',
		precio: 2.5,
		restaurante: 'McDonals',
		ingredientes: [
			'tortilla',
			'tortita',
			'pollo',
			'tomate',
			'wrap',
			'burrito',
			'mayonesa',
			'pollo rebozado',
			'pollo frito'	
		],
		descripcion: 'Disfruta de nuestro inconfundible pollo crujiente acompañado de tomate, lechuga y mayonesa. ¡Bien envuelto en una rica tortilla para que no se te escape!',
		categoria: 'rolls',
		cantidad: 'para una persona',
		pic:'nada picante',
		temp:'caliente',
		alergia:[],
		preferencia: '',
		foto: 'https://www.mcdonalds.es/sites/default/files/produits/477x360_mcwrap_0.png'
	},
	{
		nombre: 'Miso Ramen',
		precio: 9.95,
		restaurante: 'Udon',
		ingredientes: [
			'fideos',
			'caldo',
			'caldo de pollo',
			'soja',
			'miso',
			'cerdo',
			'algas wakame',
			'alga',
			'wakame',
			'nori',
			'huevo',
			'alga nori',
			'cebolleta tierna',
			'cebolleta'
		],
		descripcion: 'Fideos Ramen con caldo de pollo elaborado con soja y miso. Con láminas de cerdo marinado (chashu), algas wakame, huevo de corral semicocido y marinado, alga nori y cebolleta tierna',
		categoria: 'sopas',
		cantidad: 'para una persona',
		pic:'agridulce',
		temp:'caliente',
		alergia:[],
		preferencia: '',
		foto: 'http://www.udon.es/products/images/Miso_Soup_G_1.jpg'
	},
	{
		nombre: 'Tempura Soba',
		precio: 9.95,
		restaurante: 'Udon',
		ingredientes: [
			'caldo',
			'soba',
			'tempura',
			'verdura',
			'langostino',
			'tempura de verduras',
			'tempura de langostino',
			'alga',
			'alga nori'
		],
		descripcion: 'Soba con una deliciosa y crujiente tempura de verduras ecológicas y langostino con alga nori',
		categoria: 'tempuras',
		cantidad: 'para una persona',
		pic:'agridulce',
		temp:'caliente',
		alergia:[],
		preferencia: '',
		foto: 'http://www.udon.es/products/images/Tempura_soba_G896.jpg'
	},
	{
		nombre: 'Oyako Don',
		precio: 9.35,
		restaurante: 'Udon',
		ingredientes: [
			'arroz',
			'pollo rebozado',
			'pollo',
			'cebolla',
			'setas shiitake',
			'setas',
			'shiitake',
			'dashi',
			'huevo revuelto',
			'huevo',
			'salsa tonkatsu',
			'tonkatsu',
			'cebollino'
		],
		descripcion: 'Arroz con tiras de contramuslo de pollo rebozadas, cebolla, setas shiitake, dashi, huevo revuelto, salsa tonkatsu y cebollino',
		categoria: 'arroces',
		cantidad: 'para una persona',
		pic:'agridulce',
		temp:'caliente',
		alergia:[],
		preferencia: '',
		foto: 'http://udon.es/products/images/Oyako_Don_G.jpg'
	},
	{
		nombre: 'Yakimeshi Don',
		precio: 9.35,
		restaurante: 'Udon',
		ingredientes: [
			'arroz',
			'secreto de Cerdo',
			'cerdo',
			'setas',
			'soja',
			'maíz',
			'cebolleta',
			'zanahoria',
			'setas shiitake',
			'shiitake',
			'setas',
			'calabacín',
			'brotes de soja',
			'maíz dulce',
			'salsa de soja'
			
		],
		descripcion: 'Arroz salteado con secreto de cerdo de granja, cebolleta, zanahoria, setas shiitake, calabacín, brotes de soja y maíz dulce. Con salsa de soja Kikkoman',
		categoria: 'arroces',
		cantidad: 'para una persona',
		pic:'agridulce',
		temp:'caliente',
		alergia:[],
		preferencia: '',
		foto: 'http://www.udon.es/products/images/Yakimeshi_Don_G.jpg'
	},
	{
		nombre: 'Kaesar Asian Salad',
		precio: 8.45,
		restaurante: 'Udon',
		ingredientes: [
			'aguacate',
			'tomate cherry',
			'tomate',
			'carne',
			'pollo',
			'pechuga',
			'maíz',
			'queso',
			'pechuga de pollo',
			'salsa césar',
			'maiz tostado',
			'dashi',
			'chips de maiz',
			'cacahuete',
			'parmesano'
		],
		descripcion: 'Ensalada verde con aguacate, tomate cherry, dados de pechuga de pollo de corral rebozado con maíz tostado, salsa césar con dashi, chips crujientes de maíz, cacahuetes y parmesano rallado',
		categoria: 'ensaladas',
		cantidad: 'para una persona',
		pic:'nada picante',
		temp:'frío',
		alergia:[],
		preferencia: '',
		foto: 'http://www.udon.es/products/images/CAESARSALADG.jpg'
	},
	{
		nombre: 'Big Mac',
		precio: 4.20,
		restaurante: 'McDonals',
		ingredientes: [
			'vacuno',
			'lechuga',
			'cebolla',
			'pepinillo',
			'queso',
			'queso cheddar',
			'cheddar',
			'salsa',
			'pan de sésamo',
			'pan',
			'sésamo'
		],
		descripcion: 'Dos jugosas hamburguesas de carne 100% vacuno español, lechuga fresca y crujiente, cebolla, pepinillo, queso Cheddar fundido y nuestra inimitable salsa secreta. Todo esto envuelto en un nuevo pan de sésamo horneado al estilo tradicional.',
		categoria: 'hamburguesas',
		cantidad: 'para una persona',
		pic:'nada picante',
		temp:'caliente',
		alergia:[],
		preferencia: '',
		foto: 'https://www.mcdonalds.es/sites/default/files/produits/477x360_bm.png'
	},
	{
		nombre: 'Grand McExtreme™ Chiken Crispy Cheese',
		precio: 5.50,
		restaurante: 'McDonals',
		ingredientes: [
			'pollo',
			'pollo rebozado',
			'pollo frito',
			'crispy',
			'cebolla',
			'queso',
			'queso gouda',
			'gouda',
			'lechuga',
			'salsa de queso'
		],
		descripcion: 'Delicioso pollo crujiente 100% origen español, cebolla crispy y asada, queso Gouda, lechuga Batavia y una irresistible salsa cremosa de queso. ¿Se te ha hecho ya la boca agua?',
		categoria: 'hamburguesas',
		cantidad: 'para una persona',
		pic:'nada picante',
		temp:'caliente',
		alergia:[],
		preferencia: '',
		foto: 'https://www.mcdonalds.es/sites/default/files/produits/477x360_chickenbells.png'
	},
	{
		nombre: 'Mediterranean Tuna',
		precio: 5.55,
		restaurante: 'McDonals',
		ingredientes: [
			'atún',
			'pescado',
			'pimientos',
			'pimiento rojo',
			'pimiento amarillo',
			'lechuga',
			'croutons',
			'pan'
		],
		descripcion: '¡Nuestra base más fresca acompañado de nuestros productos más frescos! Disfruta de esta deliciosa ensalada de atún con la mejor variedad de pimientos y crujientes croutons.',
		categoria: 'ensaladas',
		cantidad: 'para una persona',
		pic:'nada picante',
		temp:'frío',
		alergia:[],
		preferencia: '',
		foto: 'https://www.mcdonalds.es/sites/default/files/produits/mediterraneantuna477.png'
	},
	{
		nombre: 'Wowburger',
		precio: 5.6,
		restaurante: 'La trocadero',
		ingredientes: [
			'remolacha',
			'mostaza',
			'pepinillos',
			'cebolla caramelizada',
			'cebolla',
			'espinacas',
			'lechuga',
			'jalapeños',
			'pan vegano'
		],
		descripcion: 'Vegan burger ecológica de remolacha, pepinillos, cebolla caramelizada, espinaca baby, lechuga trocadero, y jalapeños.',
		categoria: 'hamburguesas',
		cantidad: 'para una persona',
		pic:'picante',
		temp:'caliente',
		alergia:['sin lactosa', 'sin huevo'],
		preferencia: 'vegano',
		foto: 'http://www.latrocadero.com/wp-content/uploads/2017/10/wowburger-300x294.png'
	},
	{
		nombre: 'Setburg',
		precio: 5.95,
		restaurante: 'La trocadero',
		ingredientes: [
			'setas',
			'rúcula',
			'tomate concentrado',
			'tomate',
			'cebolla roja',
			'cebolla',
			'queso vegano',
			'queso',
			'salsa pesto vegana',
			'pesto',
			'pan vegano',
			'contundente'
		],
		descripcion: 'Vegan burger ecológica de setas, rúcula, tomate concentrado, cebolla roja, queso vegano, y salsa pesto vegana.',
		categoria: 'hamburguesas',
		cantidad: 'para una persona',
		pic:'nada picante',
		temp:'caliente',
		alergia:['sin lactosa',
			'sin huevo'],
		preferencia: 'vegano',
		foto: 'http://www.latrocadero.com/wp-content/uploads/2017/10/setburg-300x288.png'
	},
	{
		nombre: 'Setbacon',
		precio: 5.95,
		restaurante: 'La trocadero',
		ingredientes: [
			'setas',
			'bacon vegano',
			'cebolla caramelizada',
			'lechuga trocadero',
			'tomate fresco',
			'tomate',
			'lechuga',
			'curry',
			'salsa curry',
			'pan vegano',
			'cebolla'
		],
		descripcion: 'Vegan burger ecológica de setas, vegan bacon, cebolla caramelizada, lechuga trocadero, tomate fresco, y salsa curry.',
		categoria: 'hamburguesas',
		cantidad: 'para una persona',
		pic:'picante',
		temp:'caliente',
		alergia:[],
		preferencia: 'vegano',
		foto: 'http://www.latrocadero.com/wp-content/uploads/2017/10/setbacon-300x257.png'
	},
	{
		nombre: 'LTClaccic',
		precio: 5.95,
		restaurante: 'La trocadero',
		ingredientes: [
			'remolacha',
			'bacon vegano',
			'cebolla roja',
			'pepinillos',
			'rúcula',
			'lechuga trocadero',
			'lechuga',
			'pan vegano',
			'queso vegano',
			'veganesa',
			'ketchup'
		],
		descripcion: 'Vegan burger ecológica de setas, vegan bacon, cebolla caramelizada, lechuga trocadero, tomate fresco, y salsa curry.',
		categoria: 'hamburguesas',
		cantidad: 'para una persona',
		pic:'nada picante',
		temp:'caliente',
		alergia:[],
		preferencia: 'vegano',
		foto: 'http://www.latrocadero.com/wp-content/uploads/2017/10/Ltclasic-300x288.png'
	},
	{
		nombre: 'Falburger',
		precio: 5.75,
		restaurante: 'La trocadero',
		ingredientes: [
			'hamburguesa',
			'vegetal',
			'tomate',
			'cebolla',
			'vegano',
			'falafel',
			'aceitunas',
			'tomate concentrado',
			'cebolla roja',
			'pepinillos',
			'espinacas',
			'aceitunas negras',
			'pan vegano',
			'lechuga trocadero',
			'ajonesa',
			'hummus'
		],
		descripcion: 'Vegan burger ecológica de falafel, tomate concentrado, cebolla roja, pepinillos, lechuga trocadero, espinaca baby, aceitunas negras, ajonesa y hummus.',
		categoria: 'hamburguesas',
		cantidad: 'para una persona',
		pic:'nada picante',
		temp:'caliente',
		alergia:[],
		preferencia: 'vegano',
		foto: 'http://www.latrocadero.com/wp-content/uploads/2017/10/falburger-300x261.png'
	},
	{
		nombre: 'Campburg',
		precio: 5.75,
		restaurante: 'La trocadero',
		ingredientes: [
			'zanahoria',
			'cebolla',
			'pimiento rojo asado',
			'pimiento rojo',
			'pimiento',
			'cebolla caramelizada',
			'rúcula',
			'pan vegano',
			'lechuga trocadero',
			'queso vegano',
			'veganesa',
			'mostaza'
		],
		descripcion: 'Vegan burger ecológica de zanahoria y cebolla, pimiento rojo asado, cebolla caramelizada, rúcula, lechuga trocadero, queso vegano, veganesa, y mostaza.',
		categoria: 'hamburguesas',
		cantidad: 'para una persona',
		pic:'nada picante',
		temp:'caliente',
		alergia:[],
		preferencia: 'vegano',
		foto: 'http://www.latrocadero.com/wp-content/uploads/2017/10/CAMPBURG-300x254.png'
	}
]