import { Plato } from "./plato";


export const PLATOS: Plato[] = [
	{
		nombre: "Pizza Pepperone Picante",
		precio: 11.60,
		restaurante: "Tagliatella",
		ingredientes: [
			"Tomate",
			"Mozzarella",
			"Salami",
			"Salami picante"
		],
		descripcion: "Prueba la nueva Telepizza del mes Pepe Peperoni: doble ración de pepperoni y topping a base de mozzarella. ¿Podrás resistirte?",
		categoria: "Pizzas",
		cantidad: "Para compartir",
		pic: "Picante",
		temp: "Caliente",
		preferencia: ["Sin huevo", "Sin frutos secos", "Sin azucar", "Sin fructosa"],
		foto: "Https://res.cloudinary.com/hesvvq3zo/image/upload/w_1000,h_500,c_pad,q_30/v1477472361/takeaway/Le-Pizze-Pepperoni.jpg",
		valoracion: "5/5"
	},
	{
		nombre: "Pizza 4 quesos",
		precio: 12.60,
		restaurante: "Tagliatella",
		ingredientes: [
			"Tomate",
			"Grana padano",
			"Mozzarella",
			"Gorgonzola",
			"Emmental"
		],
		descripcion: "Siente en tu paladar una fusión de sabores con nuestros mejores quesos y todo esto aderezado con tomate, simplemente espectacular.",
		categoria: "Pizzas",
		cantidad: "Para compartir",
		pic: "Nada picante",
		temp: "Caliente",
		preferencia: ["Sin huevo", "Sin frutos secos", "Sin azucar", "Vegetariano", "Sin fructosa"],
		foto: "Https://res.cloudinary.com/hesvvq3zo/image/upload/w_1000,h_500,c_pad,q_30/v1477472361/takeaway/Le-Pizze-4formaggi.jpg",
		valoracion: "4/5"
	},
	{
		nombre: "Pizza Carbonara",
		precio: 9,
		restaurante: "TelePizza",
		ingredientes: [
			"Bacon",
			"Champiñon",
			"Salsa carbonara",
			"Mozzarella"
		],
		descripcion: "El inconfundible sabor de nuestra salsa carbonara con doble de bacon, champiñón y un extra de topping a base de mozzarella que la convierte en una elección segura.",
		categoria: "Pizzas",
		cantidad: "Para compartir",
		pic: "Nada picante",
		temp: "Caliente",
		preferencia: ["Sin frutos secos", "Sin azucar", "Sin fructosa"],
		foto: "Https://images.telepizza.com/vol/es/images/content/productos/pcaq_c.png",
		valoracion: "4/5"
	},
	{
		nombre: "Pizza Boloñesa",
		precio: 7,
		restaurante: "TelePizza",
		ingredientes: [
			"Carne de vacuno",
			"Mozzarella",
			"Tomate confitado",
			"Queso"
		],
		descripcion: "Doble ración de carne de vacuno, topping a base de mozzarella y extra de salsa de tomate confitado.",
		categoria: "Pizzas",
		cantidad: "Para compartir",
		pic: "Nada picante",
		temp: "Caliente",
		preferencia: ["Sin huevo", "Sin frutos secos", "Sin fructosa"],
		foto: "Https://images.telepizza.com/vol/es/images/content/productos/bolo_c.png",
		valoracion: "4/5"
	},
	{
		nombre: "Pizza Hawaiana",
		precio: 7,
		restaurante: "TelePizza",
		ingredientes: [
			"Masa fresca",
			"Jamón york",
			"Piña",
			"Mozzarella",
			"Tomate"
		],
		descripcion: "Prueba nuestra Telepizza con la receta más tropical, piña, doble de york y extra de topping a base de mozzarella y déjate seducir por los sabores más exóticos, ¡aloha!",
		categoria: "Pizzas",
		cantidad: "Para compartir",
		pic: "Nada picante",
		temp: "Caliente",
		preferencia: ["Sin huevo", "Sin frutos secos", "Sin azucar", "Sin fructosa"],
		foto: "Https://images.telepizza.com/vol/es/images/content/productos/phw_c.png",
		valoracion: "3/5"
	},
	{
		nombre: "Pizza Carbonara Cebolla",
		precio: 7,
		restaurante: "TelePizza",
		ingredientes: [
			"Masa fresca",
			"Bacon",
			"Champiñon",
			"Salsa carbonara",
			"Mozzarella",
			"Cebolla"
		],
		descripcion: "Combina tu salsa carbonara favorita con cebolla, doble de bacon y champiñón. Una mezcla que te encantará.",
		categoria: "Pizzas",
		cantidad: "Para compartir",
		pic: "Nada picante",
		temp: "Caliente",
		preferencia: ["Sin frutos secos", "Sin azucar", "Sin fructosa"],
		foto: "Https://images.telepizza.com/vol/es/images/content/productos/pcar_c.png",
		valoracion: "4/5"
	},
	{
		nombre: "Pizza Rodeo",
		precio: 7,
		restaurante: "TelePizza",
		ingredientes: [
			"Carne de vacuno",
			"Bacon",
			"Salsa steak",
			"Salsa grill",
			"Mozzarella"
		],
		descripcion: "La nueva Telepizza Rodeo compuesta por: carne de vacuno, bacon, salsa steak&grill y topping a base de mozzarella. No dejes pasar esta oportunidad y ¡Disfruta!",
		categoria: "Pizzas",
		cantidad: "Para compartir",
		pic: "Nada picante",
		temp: "Caliente",
		preferencia: ["Sin frutos secos", "Sin azucar","Sin huevo"],
		foto: "Https://images.telepizza.com/vol/es/images/content/productos/rode_c.png",
		valoracion: "4/5"
	},
	{
		nombre: "Pizza Ibérica de TelePizza",
		precio: 7,
		restaurante: "TelePizza",
		ingredientes: [
			"Jamón ibérico de cebo",
			"Tomate natural",
			"Aceite de oliva",
			"Masa fresca"
		],
		descripcion: "Una exquisita selección de jamón ibérico de cebo acompañado de finas rodajas de tomate natural y un toque de aceite de oliva sobre una crujiente masa",
		categoria: "Pizzas",
		cantidad: "Para compartir",
		pic: "Nada picante",
		temp: "Caliente",
		preferencia: ["Sin frutos secos", "Sin azucar","Sin huevo"],
		foto: "Https://images.telepizza.com/vol/es/images/content/productos/iber_c.png",
		valoracion: "5/5"
	},
	{
		nombre: "Pizza Burger",
		precio: 7,
		restaurante: "TelePizza",
		ingredientes: [
			"Queso cheddar",
			"Carne de vacuno",
			"Tomate natural",
			"Pepinillos",
			"Mozzarella",
			"Bacon cripsy",
			"Salsa burger"
		],
		descripcion: "Auténtico sabor burger en cada bocado. Queso cheddar, carne de vacuno, tomate natural y pepinillos, cubiertos con una masa con topping a base de mozzarella, bacon crispy y salsa burger.",
		categoria: "Pizzas",
		cantidad: "Para compartir",
		pic: "Nada picante",
		temp: "Caliente",
		preferencia: ["Sin frutos secos", "Sin azucar","Sin huevo"],
		foto: "Https://images.telepizza.com/vol/es/images/content/productos/p3pb_c.png",
		valoracion: "3/5"
	},
	{
		nombre: "Pizza Barbacoa Gourmet",
		precio: 7,
		restaurante: "TelePizza",
		ingredientes: [
			"5 quesos",
			"Pollo marinado",
			"Bacon ahumado",
			"Carne de vacuno",
			"Salsa barbacoa",
			"Mozzarella"
		],
		descripcion: "La mejor barbacoa de nuestra historia. Una mezcla de 5 quesos, tiras de pollo marinado, bacon ahumado, doble ración de carne de vacuno, salsa barbacoa y topping a base de mozzarella.",
		categoria: "Pizzas",
		cantidad: "Para compartir",
		pic: "Nada picante",
		temp: "Caliente",
		preferencia: ["Sin frutos secos", "Sin azucar","Sin huevo"],
		foto: "Https://images.telepizza.com/vol/es/images/content/productos/53bq_c.png",
		valoracion: "5/5"
	},
	{
		nombre: "Pizza Carbonara Gourmet Queso",
		precio: 7,
		restaurante: "TelePizza",
		ingredientes: [
			"5 quesos",
			"Masa fina",
			"Bacon",
			"Champiñón",
			"Salsa carbonara",
			"Mozzarella"
		],
		descripcion: "La mejor carbonara de nuestra historia. Una pizza mediana mezcla de 5 quesos cubierta de una masa fina con doble ración de bacon, champiñón, salsa carbonara y extra de topping a base de mozzarella",
		categoria: "Pizzas",
		cantidad: "Para compartir",
		pic: "Nada picante",
		temp: "Caliente",
		preferencia: ["Sin frutos secos", "Sin azucar","Sin huevo"],
		foto: "Https://images.telepizza.com/vol/es/images/content/productos/tkgq_c.png",
		valoracion: "5/5"
	},
	{
		nombre: "Pizza Carbonara Gourmet Cebolla",
		precio: 7,
		restaurante: "TelePizza",
		ingredientes: [
			"5 quesos",
			"Masa fina",
			"Bacon",
			"Champiñón",
			"Salsa carbonara",
			"Cebolla"
		],
		descripcion: "La mejor carbonara de nuestra historia. Una pizza mediana mezcla de 5 quesos cubierta de una masa fina con doble ración de bacon, champiñón, salsa carbonara y cebolla.",
		categoria: "Pizzas",
		cantidad: "Para compartir",
		pic: "Nada picante",
		temp: "Caliente",
		preferencia: ["Sin frutos secos", "Sin azucar","Sin huevo"],
		foto: "Https://images.telepizza.com/vol/es/images/content/productos/tkgo_c.png",
		valoracion: "5/5"
	},
	{
		nombre: "Pizza Telepizza Vulcano Nachos",
		precio: 7,
		restaurante: "TelePizza",
		ingredientes: [
			"5 quesos",
			"Masa fina",
			"Bacon",
			"Champiñón",
			"Salsa carbonara",
			"Cebolla"
		],
		descripcion: "Empieza dipeando los nachos paprika en la deliciosa fuente de queso cheddar y termina con un sabroso bocado de pizza con los ingredientes que más te gusten.",
		categoria: "Pizzas",
		cantidad: "Para compartir",
		pic: "Nada picante",
		temp: "Caliente",
		preferencia: ["Sin frutos secos", "Sin azucar","Sin huevo"],
		foto: "Https://images.telepizza.com/vol/es/images/content/productos/tkgo_c.png",
		valoracion: "2/5"
	},
	{
		nombre: "Pizza Bacon Cheeseburger",
		precio: 7,
		restaurante: "TelePizza",
		ingredientes: [
			"Masa fresca",
			"Bacon",
			"Mini hamburguesas",
			"Queso cheddar",
			"Mozzarella",
			"Salsa burger",
			"Tomate natural",
		],
		descripcion: "Si habéis soñado con una mezcla perfecta entre Telepizza y hamburguesa aquí la tenéis: salsa burger, topping a base de mozzarella, tomate natural, bacon, queso cheddar coronada con deliciosas mini hamburguesas.",
		categoria: "Pizzas",
		cantidad: "Para compartir",
		pic: "Nada picante",
		temp: "Caliente",
		preferencia: ["Sin frutos secos", "Sin azucar","Sin huevo"],
		foto: "Https://images.telepizza.com/vol/es/images/content/productos/pzbc_c.png",
		valoracion: "3/5"
	},
	{
		nombre: "Pizza Barbacoa Crème Queso",
		precio: 7,
		restaurante: "TelePizza",
		ingredientes: [
			"Masa fresca",
			"Bacon",
			"Champiñón",
			"Pollo",
			"Mozzarella",
			"Salsa barbacoa",
			"Salsa carbonara"
		],
		descripcion: "Cuando unes dos de nuestras mejores salsas el resultado es excepcional, barbacoa y carbonara acompañadas de pollo, bacon, champiñón y un extra de topping a base de mozzarella para un sabor sorprendente.",
		categoria: "Pizzas",
		cantidad: "Para compartir",
		pic: "Nada picante",
		temp: "Caliente",
		preferencia: ["Sin frutos secos", "Sin azucar"],
		foto: "Https://images.telepizza.com/vol/es/images/content/productos/pbcq_c.png",
		valoracion: "3/5"
	},
	{
		nombre: "Pizza Jalisco",
		precio: 7,
		restaurante: "TelePizza",
		ingredientes: [
			"Masa fresca",
			"Aceitunas negras",
			"Cebolla",
			"Pimiento morrón",
			"Carne de vacuno"
		],
		descripcion: "Nuestra telepizza con receta mejicana, salsa jalisco, carne de vacuno, cebolla, pimiento morrón, aceitunas negras.¡Pruébala manito!",
		categoria: "Pizzas",
		cantidad: "Para compartir",
		pic: "Picante",
		temp: "Caliente",
		preferencia: ["Sin frutos secos", "Sin azucar","Sin huevo"],
		foto: "Https://images.telepizza.com/vol/es/images/content/productos/jali_c.png",
		valoracion: "4/5"
	},
	{
		nombre: "Chicken McRoll",
		precio: 2.5,
		restaurante: "McDonals",
		ingredientes: [
			"Tortilla",
			"Tomate",
			"Mayonesa",
			"Pollo crujiente"
		],
		descripcion: "Disfruta de nuestro inconfundible pollo crujiente acompañado de tomate, lechuga y mayonesa. ¡Bien envuelto en una rica tortilla para que no se te escape!",
		categoria: "Rolls",
		cantidad: "Para una persona",
		pic: "Nada picante",
		temp: "Caliente",
		preferencia: ["Sin frutos secos", "Sin azucar","Sin huevo"],
		foto: "Https://www.mcdonalds.es/sites/default/files/produits/477x360_mcwrap_0.png",
		valoracion: "5/5"
	},
	{
		nombre: "Miso Ramen",
		precio: 9.95,
		restaurante: "Udon",
		ingredientes: [
			"Fideos",
			"Miso",
			"Caldo de pollo",
			"Soja",
			"Cerdo",
			"Algas wakame",
			"Huevo",
			"Alga nori",
			"Cebolleta tierna",
		],
		descripcion: "Fideos Ramen con caldo de pollo elaborado con soja y miso. Con láminas de cerdo marinado (chashu), algas wakame, huevo de corral semicocido y marinado, alga nori y cebolleta tierna",
		categoria: "Sopas",
		cantidad: "Para una persona",
		pic: "Agridulce",
		temp: "Caliente",
		preferencia: ["Sin frutos secos", "Sin azucar", , "Sin fructosa"],
		foto: "Http://www.udon.es/products/images/Miso_Soup_G_1.jpg",
		valoracion: "4/5"
	},
	{
		nombre: "Tempura Soba",
		precio: 9.95,
		restaurante: "Udon",
		ingredientes: [
			"Caldo",
			"Soba",
			"Tempura de verduras",
			"Tempura de langostino",
			"Alga nori"
		],
		descripcion: "Soba con una deliciosa y crujiente tempura de verduras ecológicas y langostino con alga nori",
		categoria: "Tempuras",
		cantidad: "Para una persona",
		pic: "Agridulce",
		temp: "Caliente",
		preferencia: ["Sin frutos secos", "Sin azucar","Sin huevo"],
		foto: "Http://www.udon.es/products/images/Tempura_soba_G896.jpg",
		valoracion: "5/5"
	},
	{
		nombre: "Oyako Don",
		precio: 9.35,
		restaurante: "Udon",
		ingredientes: [
			"Arroz",
			"Pollo rebozado",
			"Cebolla",
			"Setas shiitake",
			"Dashi",
			"Huevo revuelto",
			"Salsa tonkatsu",
			"Cebollino"
		],
		descripcion: "Arroz con tiras de contramuslo de pollo rebozadas, cebolla, setas shiitake, dashi, huevo revuelto, salsa tonkatsu y cebollino",
		categoria: "Arroces",
		cantidad: "Para una persona",
		pic: "Agridulce",
		temp: "Caliente",
		preferencia: ["Sin frutos secos", "Sin azucar"],
		foto: "Http://udon.es/products/images/Oyako_Don_G.jpg",
		valoracion: "4/5"
	},
	{
		nombre: "Yakimeshi Don",
		precio: 9.35,
		restaurante: "Udon",
		ingredientes: [
			"Arroz",
			"Secreto de Cerdo",
			"Maíz",
			"Cebolleta",
			"Zanahoria",
			"Setas shiitake",
			"Calabacín",
			"Brotes de soja",
			"Maíz dulce",
			"Salsa de soja Kikkoman"
		],
		descripcion: "Arroz salteado con secreto de cerdo de granja, cebolleta, zanahoria, setas shiitake, calabacín, brotes de soja y maíz dulce. Con salsa de soja Kikkoman",
		categoria: "Arroces",
		cantidad: "Para una persona",
		pic: "Agridulce",
		temp: "Caliente",
		preferencia: ["Sin frutos secos", "Sin azucar", "Sin huevo", "Sin fructosa"],
		foto: "Http://www.udon.es/products/images/Yakimeshi_Don_G.jpg",
		valoracion: "5/5"
	},
	{
		nombre: "Kaesar Asian Salad",
		precio: 8.45,
		restaurante: "Udon",
		ingredientes: [
			"Aguacate",
			"Tomate cherry",
			"Pechuga de pollo rebozado con maiz tostado",
			"Salsa césar",
			"Dashi",
			"Chips de maiz",
			"Cacahuete",
			"Parmesano"
		],
		descripcion: "Ensalada verde con aguacate, tomate cherry, dados de pechuga de pollo de corral rebozado con maíz tostado, salsa césar con dashi, chips crujientes de maíz, cacahuetes y parmesano rallado",
		categoria: "Ensaladas",
		cantidad: "Para una persona",
		pic: "Nada picante",
		temp: "Frío",
		preferencia: ["Sin frutos secos", "Sin azucar", "Sin huevo"],
		foto: "Http://www.udon.es/products/images/CAESARSALADG.jpg",
		valoracion: "4/5"
	},
	{
		nombre: "Big Mac",
		precio: 4.20,
		restaurante: "McDonals",
		ingredientes: [
			"Carne de vacuno",
			"Lechuga",
			"Cebolla",
			"Pepinillo",
			"Queso cheddar",
			"Pan de sésamo"
		],
		descripcion: "Dos jugosas hamburguesas de carne 100% vacuno español, lechuga fresca y crujiente, cebolla, pepinillo, queso Cheddar fundido y nuestra inimitable salsa secreta. Todo esto envuelto en un nuevo pan de sésamo horneado al estilo tradicional.",
		categoria: "Hamburguesas",
		cantidad: "Para una persona",
		pic: "Nada picante",
		temp: "Caliente",
		preferencia: ["Sin azucar", "Sin huevo"],
		foto: "Https://www.mcdonalds.es/sites/default/files/produits/477x360_bm.png",
		valoracion: "4/5"
	},
	{
		nombre: "Grand McExtreme™ Chiken Crispy Cheese",
		precio: 5.50,
		restaurante: "McDonals",
		ingredientes: [
			"Pollo crujiente",
			"Cebolla crispy",
			"Queso gouda",
			"Lechuga",
			"Salsa de queso"
		],
		descripcion: "Delicioso pollo crujiente 100% origen español, cebolla crispy y asada, queso Gouda, lechuga Batavia y una irresistible salsa cremosa de queso. ¿Se te ha hecho ya la boca agua?",
		categoria: "Hamburguesas",
		cantidad: "Para una persona",
		pic: "Nada picante",
		temp: "Caliente",
		preferencia:["Sin huevo", "Sin lactosa"],
		foto: "Https://www.mcdonalds.es/sites/default/files/produits/477x360_chickenbells.png",
		valoracion: "5/5"
	},
	{
		nombre: "Mediterranean Tuna",
		precio: 5.55,
		restaurante: "McDonals",
		ingredientes: [
			"Atún",
			"Pimiento rojo",
			"Pimiento amarillo",
			"Lechuga",
			"Croutons",
			"Pan"
		],
		descripcion: "¡Nuestra base más fresca acompañado de nuestros productos más frescos! Disfruta de esta deliciosa ensalada de atún con la mejor variedad de pimientos y crujientes croutons.",
		categoria: "Ensaladas",
		cantidad: "Para una persona",
		pic: "Nada picante",
		temp: "Frío",
		preferencia: ["Sin huevo", "Sin lactosa", "Sin frutos secos", "Sin fructosa"],
		foto: "Https://www.mcdonalds.es/sites/default/files/produits/mediterraneantuna477.png",
		valoracion: "3/5"
	},
	{
		nombre: "Wowburger",
		precio: 5.6,
		restaurante: "La trocadero",
		ingredientes: [
			"Remolacha",
			"Mostaza",
			"Pepinillos",
			"Cebolla caramelizada",
			"Espinacas",
			"Lechuga",
			"Jalapeños",
			"Pan vegano"
		],
		descripcion: "Vegan burger ecológica de remolacha, pepinillos, cebolla caramelizada, espinaca baby, lechuga trocadero, y jalapeños.",
		categoria: "Hamburguesas",
		cantidad: "Para una persona",
		pic: "Picante",
		temp: "Caliente",
		preferencia:["Vegano", "Sin huevo", "Vegetariano", "Sin lactosa", "Sin frutos secos"],
		foto: "Http://www.latrocadero.com/wp-content/uploads/2017/10/wowburger-300x294.png",
		valoracion: "4/5"
	},
	{
		nombre: "Setburg",
		precio: 5.95,
		restaurante: "La trocadero",
		ingredientes: [
			"Hamburguesa de setas",
			"Rúcula",
			"Tomate concentrado",
			"Cebolla roja",
			"Queso vegano",
			"Salsa pesto vegana",
			"Pesto",
			"Pan vegano"
		],
		descripcion: "Vegan burger ecológica de setas, rúcula, tomate concentrado, cebolla roja, queso vegano, y salsa pesto vegana.",
		categoria: "Hamburguesas",
		cantidad: "Para una persona",
		pic: "Nada picante",
		temp: "Caliente",
		preferencia: ["Vegano", "Sin huevo", "Vegetariano", "Sin lactosa"],
		foto: "Http://www.latrocadero.com/wp-content/uploads/2017/10/setburg-300x288.png",
		valoracion: "3/5"
	},
	{
		nombre: "Setbacon",
		precio: 5.95,
		restaurante: "La trocadero",
		ingredientes: [
			"Hamburguesa de setas",
			"Bacon vegano",
			"Cebolla caramelizada",
			"Lechuga trocadero",
			"Tomate fresco",
			"Salsa curry",
			"Pan vegano"
		],
		descripcion: "Vegan burger ecológica de setas, vegan bacon, cebolla caramelizada, lechuga trocadero, tomate fresco, y salsa curry.",
		categoria: "Hamburguesas",
		cantidad: "Para una persona",
		pic: "Picante",
		temp: "Caliente",
		preferencia:["Vegano", "Sin huevo", "Vegetariano", "Sin lactosa", "Sin frutos secos"],
		foto: "Http://www.latrocadero.com/wp-content/uploads/2017/10/setbacon-300x257.png",
		valoracion: "5/5"
	},
	{
		nombre: "LTClaccic",
		precio: 5.95,
		restaurante: "La trocadero",
		ingredientes: [
			"Remolacha",
			"Bacon vegano",
			"Cebolla roja",
			"Pepinillos",
			"Rúcula",
			"Lechuga trocadero",
			"Lechuga",
			"Pan vegano",
			"Queso vegano",
			"Veganesa",
			"Ketchup"
		],
		descripcion: "Vegan burger ecológica de setas, vegan bacon, cebolla caramelizada, lechuga trocadero, tomate fresco, y salsa curry.",
		categoria: "Hamburguesas",
		cantidad: "Para una persona",
		pic: "Nada picante",
		temp: "Caliente",
		preferencia: ["Vegano", "Sin huevo", "Vegetariano", "Sin lactosa", "Sin frutos secos"],
		foto: "Http://www.latrocadero.com/wp-content/uploads/2017/10/Ltclasic-300x288.png",
		valoracion: "4/5"
	},
	{
		nombre: "Falburger",
		precio: 5.75,
		restaurante: "La trocadero",
		ingredientes: [
			"Falafel",
			"Tomate concentrado",
			"Cebolla roja",
			"Pepinillos",
			"Espinacas",
			"Aceitunas negras",
			"Lechuga trocadero",
			"Ajonesa",
			"Hummus"
		],
		descripcion: "Vegan burger ecológica de falafel, tomate concentrado, cebolla roja, pepinillos, lechuga trocadero, espinaca baby, aceitunas negras, ajonesa y hummus.",
		categoria: "Hamburguesas",
		cantidad: "Para una persona",
		pic: "Nada picante",
		temp: "Caliente",
		preferencia: ["Vegano", "Sin huevo", "Vegetariano", "Sin lactosa", "Sin frutos secos", "Sin fructosa"],
		foto: "Http://www.latrocadero.com/wp-content/uploads/2017/10/falburger-300x261.png",
		valoracion: "4/5"
	},
	{
		nombre: "Campburg",
		precio: 5.75,
		restaurante: "La trocadero",
		ingredientes: [
			"Zanahoria",
			"Cebolla",
			"Pimiento rojo asado",
			"Pimiento rojo",
			"Cebolla caramelizada",
			"Rúcula",
			"Pan vegano",
			"Lechuga trocadero",
			"Queso vegano",
			"Veganesa",
			"Mostaza"
		],
		descripcion: "Vegan burger ecológica de zanahoria y cebolla, pimiento rojo asado, cebolla caramelizada, rúcula, lechuga trocadero, queso vegano, veganesa, y mostaza.",
		categoria: "Hamburguesas",
		cantidad: "Para una persona",
		pic: "Nada picante",
		temp: "Caliente",
		preferencia: ["Vegano", "Sin huevo", "Vegetariano", "Sin lactosa", "Sin frutos secos"],
		foto: "Http://www.latrocadero.com/wp-content/uploads/2017/10/CAMPBURG-300x254.png",
		valoracion: "3/5"
	},
	{
		nombre: "Salmon avocado roll",
		precio: 4.25,
		restaurante: "Udon",
		ingredientes: [
			"Salmón", 
			"Aguacate", 
			"Tartar de mango", 
			"Salsa de mango", 
			"Salsa de sésamo", 
			"Brotes"
		],
		descripcion: "Cuatro noodle rolls con salmón, aguacate, tartar de mango, salsa de sésamo y brotes",
		categoria: "Sushi",
		cantidad: "Para una persona",
		pic: "Nada picante",
		temp: "Frio",
		preferencia: ["Sin huevo", "Sin lactosa"],
		foto: "Http://www.udon.es/products/images/Salmon_Avocado_Roll_G.jpg",
		valoracion: "5/5"
	}, 
	{
		nombre: "Tatiyaki de salmón",
		precio: 5.25,
		restaurante: "Udon",
		ingredientes: [
			"Salmón marinado", 
			"Soja", 
			"Limón", 
			"Wasabi", 
			"Aceite de sésamo", 
			"Mirin",
			"Salsa teriyaki", 
			"Dados de aguacate con sésamo"
		],
		descripcion: "Salmón marinado con soja, limón, wasabi, aceite de sésamo y mirin. Marcado a la plancha, fileteado y acompañado con salsa teriyaki y dados de aguacate con sésamo",
		categoria: "Pescados",
		cantidad: "Para una persona",
		pic: "Picante",
		temp: "Frio",
		preferencia: ["Sin huevo", "Sin lactosa"],
		foto: "Http://www.udon.es/products/images/Tataki_Salmon_G3606.jpg",
		valoracion: "4/5"
	},
	{
		nombre: "Tataki de ternera",
		precio: 6.25,
		restaurante: "Udon",
		ingredientes: [
			"Lomo de buey macerado",
			"Soja",
			"Mirin",
			"Aceite de sésamo",
			"Chips de espinacas", 
			"Salsa teriyaki"
		],
		descripcion: "Lomo de buey macerado con soja, mirin y aceite de sésamo acompañado de chips de espinacas. Marcado a la plancha, fileteado y acompañado con salsa teriyaki",
		categoria: "Carnes",
		cantidad: "Para una persona",
		pic: "Nada picante",
		temp: "Frio",
		preferencia: ["Sin huevo", "Sin lactosa"],
		foto: "Http://www.udon.es/products/images/Tataki_Buey_G.jpg",
		valoracion: "4/5"
	},
	{
		nombre: "Top Sándwich York",
		precio: 4.95,
		restaurante: "Telepizza",
		ingredientes: [
			"Jamón york", 
			"Salsa especial", 
			"Bacon crispy", 
			"Queso edam", 
			"Queso cheddar"
		],
		descripcion: "¿Es una hamburguesa? ¿Es un bocadillo? Es nuestro sándwich de york acompañado con una salsa especial, york, bacon crispy,loncha queso edam y cheddar.",
		categoria: "Bocadillos",
		cantidad: "Para una persona",
		pic: "Nada picante",
		temp: "Caliente",
		preferencia: ["Sin huevo", "Sin lactosa"],
		foto: "Https://images.telepizza.com/vol/es/images/content/productos/tsj_c.png",
		valoracion: "4/5"
	}
]
